vim.g.mapleader = ' '
vim.g.maplocalleader = '\\'

-- experimental UI for 0.12
require('vim._extui').enable {}
vim.opt.cmdheight = 0

require 'config.options'
require 'config.keymaps'
require 'config.auto-commands'
require 'config.filetype'
require 'config.lsp'

require 'plugins.lsp'
require 'plugins.completions'
require 'plugins.colorscheme'
require 'plugins.navigation'
require 'plugins.formatting'
require 'plugins.treesitter'
require 'plugins.git'
require 'plugins.bindings '
require 'plugins.colors '
require 'plugins.completion '
require 'plugins.csvview '
require 'plugins.database '
require 'plugins.diagnostics '
require 'plugins.editor '
require 'plugins.explorer '
require 'plugins.git '
require 'plugins.lang '
require 'plugins.markdown '
require 'plugins.multicursor '
require 'plugins.picker '
require 'plugins.schemastore '
require 'plugins.session '
require 'plugins.statusline '
require 'plugins.tmux '
require 'plugins.treesitter '
require 'plugins.undo '
