-- vim.keymap.set('n', '<localleader>E', '<cmd>Markview Enable<cr>')
-- vim.keymap.set('n', '<localleader>D', '<cmd>Markview Disable<cr>')
-- vim.keymap.set('n', '<localleader>T', '<cmd>Markview Toggle<cr>')
--
-- vim.keymap.set('n', '<localleader>e', '<cmd>Markview enable<cr>')
-- vim.keymap.set('n', '<localleader>d', '<cmd>Markview disable<cr>')
-- vim.keymap.set('n', '<localleader>t', '<cmd>Markview toggle<cr>')
